FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN chmod +x mvnw || true

RUN ./mvnw package -DskipTests || mvn package -DskipTests

EXPOSE 8080

CMD ["java","-jar","target/protein-project-1.0.jar"]
